<?php

namespace InstaFetcherTests\Unit\DataAccess\Repository\InstaUserHttpRepositoryTest\GetUserByHandle;

use InstaFetcherTests\Unit\DataAccess\Repository\InstaUserHttpRepositoryTest\Given_User_Gets_Insta_User_By_Handle;
use InstaFetcherTests\Unit\DataAccess\Repository\InstaUserHttpRepositoryTest\InstaUserHttpRepositoryTestCase;
use PHPUnit\Framework\TestCase;

class When_No_Facebook_Pages_Are_Retrieved_Test
{

}
