name: tests

on:
  push:
    branches:
      - '*'

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v2

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        run: composer install

      - name: Create enviroment variables
        run: |
          touch .env

      - name: Run unit tests
        run: vendor/bin/phing unit_tests

  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v2

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        run: composer install

      - name: Create enviroment variables
        run: |
          touch .env

      - name: Run integration tests
        run: vendor/bin/phing integration_tests

  smoke-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v2

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        run: composer install

      - name: Create enviroment variables
        run: |
          touch .env
          echo "BASE_URL=https://graph.facebook.com/v9.0/" >> .env
          echo APP_SECRET=${{ secrets.APP_SECRET }} >> .env
          echo APP_ID=${{ secrets.APP_ID }} >> .env
          echo OPEN_GRAPH_USER_TOKEN=${{ secrets.OPEN_GRAPH_USER_TOKEN }} >> .env
          echo OPEN_GRAPH_USER_PAGE_ID=${{ secrets.OPEN_GRAPH_USER_PAGE_ID }} >> .env

      - name: Run smoke tests
        run: vendor/bin/phing smoke_tests